name: social_reporter
description: A new Flutter project.
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.2

  # Storage
  shared_preferences: ^2.0.13

  # Auth
  google_sign_in: ^5.2.4
  extension_google_sign_in_as_googleapis_auth: ^2.0.4

  # APIs
  firebase_core: ^1.13.1
  firebase_storage: ^10.2.9
  googleapis: ^8.1.0
  tdlib: # 1.6.0
    git:
      url: https://github.com/OlehMarchenko95/tdlib.git
      ref: bf2247d1e2ea0c7f7c5e6f324bced6cefdca3a88

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
